// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  profileSidebar: [
    {
      type: 'doc',
      label: 'Profile',
      id: 'about-me',
    }
  ],
  
  toolingSidebar: [
    {
      type: 'doc',
      label: 'Overview',
      id: 'intro',
    },
    {
      type: 'category',
      label: 'Documentation Tooling',
      items:[
        {
      type: 'doc',
      label: 'Introduction',
      id: 'documentation-tooling/intro',
    },
    {
      type: 'category',
      label: 'Microcks',
       link: {
        type: 'doc',
        id: 'documentation-tooling/microcks-overview'
      },
      items: [
        'documentation-tooling/getting-started',
        {
          type:'category',
          label: 'How To Guides',
          items: [
            {
            type: 'category',
            label: 'Automation',
            items: [ 
              'documentation-tooling/how-to-guides/automation/connecting-to-microcks-api',
              'documentation-tooling/how-to-guides/automation/using-microcks-cli',]
            }
            
          ],
            }
          ]
        }

      ]
    },

    {
      type: 'category',
      label: 'API Documentation',
      items:[
        {
      type: 'doc',
      label: 'Introduction',
      id: 'api-documentation/intro',
       },
       {
        type: 'doc',
        label: 'Getting Started',
        id: 'api-documentation/getting-started',
       },
       {
       type: 'category',
        label: 'Reference',
        items: [
          require('./docs/api-documentation/reference/sidebar.ts')
        ],
     
       }
       
      ]
    },
    {
      type: 'category',
      label: 'Docs Automation',
      items:[
        {
      type: 'doc',
      label: 'Overview',
      id: 'docs-automation/intro',
       },
      ]
    },
    // {
    //   type: 'category',
    //   label: 'AI Documentation',
    //   items:[
    //     {
    //   type: 'doc',
    //   label: 'Introduction',
    //   id: 'ai-documentation/intro',
    //    },
    //    {
    //     type: 'doc',
    //     label: 'Model Card',
    //     id: 'ai-documentation/model_card',
    //    }
    //   ]
    // },
    {
      
      type: 'category',
      label: 'DevOps & Cloud Documentation',
      items:[
        {
          type: 'doc',
          label: 'Introduction',
          id: 'devops-cloud-documentation/intro',
        },
        {
          type: 'doc',
          label: 'Overview',
          id: 'devops-cloud-documentation/overview',
        },
        {
          type: 'doc',
          label: 'Setup',
          id: 'devops-cloud-documentation/setup',
        },
        {
          type: 'doc',
          label: 'Step-by-Step Guide',
          id: 'devops-cloud-documentation/step_by_step',
        },
        {
          type: 'doc',
          label: 'Troubleshooting',
          id: 'devops-cloud-documentation/troubleshooting',
        },
        {
          type: 'doc',
          label: 'Summary',
          id: 'devops-cloud-documentation/summary',
        },
        {
          type: 'doc',
          label: 'Reflection',
          id: 'devops-cloud-documentation/reflection',
        },
      ]
    }
  ],
};

export default sidebars;
